'''
Created on Nov 4, 2018

JSON constants that are used in requests.

@author: agagaleza
'''
class RequestConstants(object):
    '''
    
    '''
    #request json body
    JSON_STATUS_AVAILABLE = 'available'
    JSON_STATUS_PENDING = 'pending'
    JSON_STATUS_SOLD = 'sold'
    JSON_NAME = 'name'
    JSON_PHOTOURLS = 'photoUrls'
    JSON_STATUS = 'status'
    JSON_CATEGORY = 'category'
    JSON_TAGS = 'tags'
    JSON_TAG = 'tag'
    JSON_UPLOAD_IMAGE = 'uploadImage'
    JSON_ID = 'id'
    JSON_MESSAGE = 'message'
    JSON_GET = 'GET'
    JSON_FINDBYSTATUS = 'GET FINDBYSTATUS'
    JSON_DELETE = 'DELETE'
    JSON_POST = 'POST'
    JSON_PUT = 'PUT'
    JSON_UPLOAD = 'POST UPLOADIMAGE'
    JSON_USER_GET_LOGIN = 'GET LOGIN'
    JSON_REQUEST_STATUS = '?status='
    JSON_URL = 'basic_url'
    JSON_CONTENT_TYPE = 'Content-Type'
    JSON_ACCEPT = 'accept'
    JSON_ENDPOINT = 'api_endpoint'
    JSON_RESPONSE = 'response_full'
    JSON_RESPONSE_CODE = 'expected_response_code'
    JSON_RESPONSE_CONTENT_TYPE =  'expected_response_content_type'
    JSON_API_KEY =  'api_key'
    JSON_USER_NAME = 'username'
    JSON_USER_FIRST_NAME = 'firstName'
    JSON_USER_LAST_NAME = 'lastName'
    JSON_USER_EMAIL = 'email'
    JSON_USER_PASSWORD = 'password'
    JSON_USER_PHONE = 'phone'
    JSON_USER_STATUS = 'userStatus'
    API_KEY = 'galeza'
    PARAMS_USERNAME = 'username'
    PARAMS_PASSWORD = 'password'
    